### ISSUE TITLE
[Incomplete instructions] For Windows X Elite 

### ISSUE THREAD

**Issue by BrickDesignerNL** [quic/ai-hub-apps#12]
https://github.com/quic/ai-hub-apps/tree/main/apps/windows/python/Whisper

Instruction is not correct.
It doesn't checkout the repo, so running the requirements.txt will not work without extra steps.

By the way we can't re-open a issue ;)

**Comment by mestrona-3** [comment]
Hi @BrickDesignerNL , I'll let @kory comment on Whisper instructions... however, I wanted to invite you to our [Slack Community](https://aihub.qualcomm.com/community/slack). Posting questions there is alot easier to have collaborative discussion with our team. Github issues is typically used for specific typos, bugs or changes that need to be made to a specific file.

**Comment by mestrona-3** [comment]
Not being able to re-open issues is unfortunately not in our control, it's an organization wide setting

**Comment by kory** [comment]
Thanks for the feedback! We'll take a look at how to better inform users they need to clone the repo first.
