### ISSUE TITLE
Can the model be deployed to the Micro NPU in the Sensing Hub?

### ISSUE THREAD

**Issue by AndreaChiChengdu** [quic/ai-hub-apps#13]
Supported compute units
CPU, GPU, NPU (includes [hexagon HTP](https://developer.qualcomm.com/hardware/qualcomm-innovators-development-kit/ai-resources-overview/ai-hardware-cores-accelerators))

Hi, 
I noticed that my SM8750 sensing hub includes a micro NPU and DSP. Is it supported to deploy on the sensing hub? Thank you.

**Comment by mestrona-3** [comment]
HI @AndreaChiChengdu , can you give us a bit more information on your question? [Qualcomm AI Hub ](https://aihub.qualcomm.com) supports compiling, profiling and inference jobs across various devices, including the SM8750 (Snapdragon 8 Elite). We encourage you to submit a model on this device via AI Hub and you can use our options to target specific compute units. Check out more, [here around our --compute_unit flag ](https://app.aihub.qualcomm.com/docs/hub/api.html)
