### ISSUE TITLE
Genie C API : Sample android app

### ISSUE THREAD

**Issue by taeyeonlee** [quic/ai-hub-apps#2]
Qualcomm released the new version (2.25.0.240728) of qualcomm_ai_engine_direct(A.K.A QNN).
There is Qualcomm Genie SDK which includes Genie C API.
Could you please share a sample app using Genie C API ?

**Comment by mestrona-3** [comment]
Hi Taeyeon Lee, thank you for the feature request. As mentioned on slack, we are working on this. We kindly request in the future that you submit this type of request in one location (Slack, AI Hub Apps Github and AI Hub Models Github) as they are all monitored by the same team 😄. We are actively working on this and will share it as soon as possible.
