### ISSUE TITLE
Example on Video

### ISSUE THREAD

**Issue by pavloshargan** [quic/ai-hub-apps#27]
Hi, it would be great if you could provide an example of running a model on a video using a hardware-accelerated decoder with MediaCodecs

**Comment by mestrona-3** [comment]
Hi @pavloshargan , thanks for the question! We'd recommend asking questions related to AI Hub via our [Slack Community](https://aihub.qualcomm.com/community/slack) for faster response times :)

That being said, it seems like you're looking for an example to add on to the [MediaCodec Extensions docs](https://docs.qualcomm.com/bundle/publicresource/topics/80-56386-10/mediacodec_extensions.html)... If we've misunderstood your question and this is not the case and you're interested a specific video model please let us know. This request is unfortunately outside of the scope of our team as we focus on running neural networks through this repo, and help users bring NNs on device with [AI Hub Models](https://aihub.qualcomm.com). We also have our platform, to BYOM (bring your own model) to be compiled, optimized and test performance and inference on real-devices.
