### ISSUE TITLE
EOF occurred in violation of protocol uploading splits

### ISSUE THREAD

**Issue by MikeYeager** [quic/ai-hub-apps#8]
I've been trying to process the llama_v3_8b_chat model following the LLM on Genie tutorial on GitHub. Most of it goes OK, I've split the model locally in aimet format, but then it tries to upload the splits to QC AI Hub and the upload of the second split fails saying "EOF occurred in violation of protocol". https://github.com/quic/ai-hub-apps/tree/main/tutorials/llm_on_genie
![image](https://github.com/user-attachments/assets/a2cd179e-8376-4d9f-ab90-40ac8415d67a)

**Comment by mestrona-3** [comment]
Closing as we discussed this on slack with @MikeYeager

**Comment by MikeYeager** [comment]
FYI, the result was that there is a bug in Python 3.10 on Windows ARM64 that causes the uploads to fail. Newer versions of Python have a dependency on h5py that is not yet supported on Windows ARM64. It may work if you install x86 Python and run it through translation on ARM. Didn't test.
